from __future__ import annotations

class MarkupMeta(type):
    def __neg__(self) -> Element: ...
    def __invert__(self) -> Element: ...

class Element(metaclass=MarkupMeta):
    def __init__(self, *args, **kwargs): ...
    def __add__(self, other) -> Element: ...
    def __sub__(self, other) -> Element: ...
    def __call__(self, *args, **kwargs) -> Element: ...
    def __truediv__(self, other) -> Element: ...
    def __gt__(self, other) -> Element: ...
    def __lt__(self, other) -> Element: ...

xml = Element()
_ = xml

class div(Element): ...
class img(Element): ...
class ul(Element): ...
class li(Element): ...
